// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DynamicList: typeof import('./src/components/dynamicList/index.vue')['default']
    NoteList: typeof import('./src/components/noteList/index.vue')['default']
  }
}

export { }
